server:
  port: 6000

spring:
  application:
    name: edge-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  debug:
    request: true
  routes:
    payment-service:
        path: /payment-service/**
        serviceId: payment-service
        stripPrefix: true
    customerinfo-service:
        path: /customerinfo-service/**
        serviceId: customerinfo-service
        stripPrefix: true
